### ISSUE TITLE
Plugin install Scripting

### ISSUE THREAD

**Issue by DSMaVie** [QuITAC/wordpress#4]
The Plugin for the SSO needs a reinstallation. Time to write a script for that.

**Comment by DSMaVie** [comment]
The plugin just lays in the plugin folder. The idea would be to commit the entirety of wp to version control, including the plugins and themes we need.

**Comment by DSMaVie** [comment]
Right now the files in the wordpress folder belong to the www-data group. this probably needs a config change in the compose to map the uid/gid in the right way.

**Comment by DSMaVie** [comment]
A simple mapping of uids etc does not solve this unfortunately.  the problem persists when pushing with git (rn only root is possible in doing that) and otherwise there is not much use in mapping. maybe the internet has solutions for that

**Comment by Numifox** [comment]
Plugins are now simply upload to git.
